---
title: "Death Days"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(data.table)
library(tidyverse)
```


```{r read_data, cache = TRUE}
# We are using the data.table package because it is faster. Note how it also
# provides a handier error message about the bad line in the file.

x <- data.table::fread("~/bunmd_v2.csv") %>% 
  as_tibble() %>% 
  select(ssn, lname, dyear, dmonth, dday, byear, bmonth, bday)
```
```{r small_data_sample}
small <- x %>%
  slice_sample(prop = 0.01) %>%
  drop_na(0)

small %>%
  drop_na(dday) %>%
  group_by(dyear, dday) %>%
  summarize(death = n(),
            .groups = "drop") %>%
  filter (dday %in% c("1", "2")) %>%
  pivot_wider(names_from = dday, values_from = death) %>%
  rename(d1 = "1", d2 = "2") %>%
  mutate(d1_d2_ratio = d1/d2) %>%
  ggplot(mapping = aes(x = dyear, y = d1_d2_ratio)) +
  geom_point() +
  geom_smooth( method = "lm")

# small_april_15th <- small_april %>%
#   group_by(dyear) %>%
#   filter(dday == 15) %>%
#   summarize(totaldeaths = n())
  
```
```{r bigdata_plot}
x %>%
  drop_na(dday,dyear) %>%
  group_by(dyear, dday) %>%
  summarize(death = n(),
            .groups = "drop") %>%
  filter (dday %in% c("1", "2")) %>%
  pivot_wider(names_from = dday, values_from = death) %>%
  rename(d1 = "1", d2 = "2") %>%
  mutate(d1_d2_ratio = d1/d2) %>%
  drop_na() %>%
  ggplot(mapping = aes(x = dyear, y = d1_d2_ratio)) +
  geom_point()
```


